### ISSUE TITLE
Cassandra Channel || Able to receive message at engine side for update/delete operation when record is not present

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#94]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |   6.3.0              |
| OS Type?     |                 |
| OS Version?           |                 |

If a record is not present in Cassandra DB and update/delete operation is being performed then also event triggers at engine side. As we have CDC enabled and data is not present inside DB, shouldn't we receive any kind of message from the topic (in case of data not present)

[authProvider_none_V6.log](https://github.com/TIBCOSoftware/be-contribution/files/11321794/authProvider_none_V6.log)

**Comment by rakulkar-tibco** [comment]
In Cassandra - Unlike in SQL, UPDATE does not check the prior existence of the row by default. The row is created if none existed before, and updated otherwise. Furthermore, there is no means of knowing which action occurred.

Reference : https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#update-statement

**Comment by praagraw-tibco** [comment]
Closed as per comment
