### ISSUE TITLE
Cassandra Store Catalog Function || Few new functions related to QueryOptions are not visible in Cassandra Store Catalog Functions

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#97]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |      6.3.0           |
| OS Type?     |      NA           |
| OS Version?           |      NA           |

### What is the actual behavior?
Below 2 new functions related to QueryOptions are not visible in Cassandra Store Catalog Functions
Store.QueryOptions.Cassandra.readTimeoutMillis (Object queryOptions, int readTimeoutMillis)
Store.QueryOptions.Cassandra.setConsistency(Object queryOptions, String consistencyLevel)

### Please provide log files.
<img width="710" alt="QueryOptionFunctions" src="https://user-images.githubusercontent.com/127474249/235598209-2d363b32-6dce-4f68-9fe6-dd8450fe6418.PNG">

**Comment by rakulkar-tibco** [comment]
With the latest DataStax java driver, The configuration has been completely revamped. Instead of ad-hoc configuration classes, the default mechanism is now file-based. This is a better choice for most deployments since it allows configuration changes without recompiling the client application.

Users can place an application.conf/reference.conf in your application’s classpath to override options selectively.

For more details refer:

https://docs.datastax.com/en/developer/java-driver/4.14/upgrade_guide/#configuration

 - [https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/configuration/reference/]

Updated confluence as well accordingly.
